import { Metadata } from 'next';
import '@/shared/styles/globals.scss';
import Footer from '@/shared/ui/footer/Footer';
import JotaiProvider from '@/shared/ui/jotai/JotaiProvider';
import ModalPortal from '@/shared/ui/modal/ModalPortal';
import RootContainer from '@/shared/ui/rootContainer/RootContainer';
import ReactQueryProvider from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <JotaiProvider>
            <ModalPortal />
            <RootContainer>
              {children}
              <Footer />
            </RootContainer>
          </JotaiProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
